services:
  # ***** database *****
  mongo:
    # This service name will be also used as hostname for MONGODB_URI
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    # ports:
    #   - 27017:27017
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ./data/qdrant:/qdrant/storage
    restart: always

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # Redis for job queue
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
  # /***** database *****
 
  # ***** backend *****
  fastapp:
    build:
      context: ./fastapp
    depends_on:
      - mongo
      - postgres
      - redis
      - qdrant
    env_file:
      - ./fastapp/.env
    volumes:
      - ./fastapp/.env:/fastapp/.env:ro
      - ./fastapp/app:/fastapp/app:ro
      - ./fastapp/app/pyproject.toml:/fastapp/app/pyproject.toml:ro
    restart: always

  # /***** backend ***** 

  # ***** frontend *****
  ui:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./ui/dist:/usr/share/nginx/html:ro
      - ./ui/dist/certs:/etc/nginx/certs:ro
      - ./ui/dist/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  # /***** frontend *****

volumes:
  data:
  ollama_data:


networks:
  app_network:
    driver: bridge
