export interface Country {
    name: string;
    code: string;
    code3: string;
    numeric: number;
    langueages: string[]; // Optional field for language
}
// Lọc trùng các quốc gia theo code (ưu tiên quốc gia xuất hiện đầu tiên)
export const countries: Country[] = [
    { "name": "Afghanistan", "code": "AF", "code3": "AFG", "numeric": 4, "langueages": ["fa", "ps", "uz"] },
    { "name": "Albania", "code": "AL", "code3": "ALB", "numeric": 8, "langueages": ["sq"] },
    { "name": "Algeria", "code": "DZ", "code3": "DZA", "numeric": 12, "langueages": ["ar", "fr"] },
    { "name": "American Samoa", "code": "AS", "code3": "ASM", "numeric": 16, "langueages": ["en", "sm"] },
    { "name": "Andorra", "code": "AD", "code3": "AND", "numeric": 20, "langueages": ["ca"] },
    { "name": "Angola", "code": "AO", "code3": "AGO", "numeric": 24, "langueages": ["pt"] },
    { "name": "Anguilla", "code": "AI", "code3": "AIA", "numeric": 660, "langueages": ["en"] },
    { "name": "Antarctica", "code": "AQ", "code3": "ATA", "numeric": 10, "langueages": [] },
    { "name": "Antigua and Barbuda", "code": "AG", "code3": "ATG", "numeric": 28, "langueages": ["en"] },
    { "name": "Argentina", "code": "AR", "code3": "ARG", "numeric": 32, "langueages": ["es"] },
    { "name": "Armenia", "code": "AM", "code3": "ARM", "numeric": 51, "langueages": ["hy"] },
    { "name": "Aruba", "code": "AW", "code3": "ABW", "numeric": 533, "langueages": ["nl", "pap"] },
    { "name": "Australia", "code": "AU", "code3": "AUS", "numeric": 36, "langueages": ["en"] },
    { "name": "Austria", "code": "AT", "code3": "AUT", "numeric": 40, "langueages": ["de"] },
    { "name": "Azerbaijan", "code": "AZ", "code3": "AZE", "numeric": 31, "langueages": ["az"] },
    { "name": "Bahamas (the)", "code": "BS", "code3": "BHS", "numeric": 44, "langueages": ["en"] },
    { "name": "Bahrain", "code": "BH", "code3": "BHR", "numeric": 48, "langueages": ["ar"] },
    { "name": "Bangladesh", "code": "BD", "code3": "BGD", "numeric": 50, "langueages": ["bn"] },
    { "name": "Barbados", "code": "BB", "code3": "BRB", "numeric": 52, "langueages": ["en"] },
    { "name": "Belarus", "code": "BY", "code3": "BLR", "numeric": 112, "langueages": ["be", "ru"] },
    { "name": "Belgium", "code": "BE", "code3": "BEL", "numeric": 56, "langueages": ["nl", "fr", "de"] },
    { "name": "Belize", "code": "BZ", "code3": "BLZ", "numeric": 84, "langueages": ["en", "es"] },
    { "name": "Benin", "code": "BJ", "code3": "BEN", "numeric": 204, "langueages": ["fr"] },
    { "name": "Bermuda", "code": "BM", "code3": "BMU", "numeric": 60, "langueages": ["en"] },
    { "name": "Bhutan", "code": "BT", "code3": "BTN", "numeric": 64, "langueages": ["dz"] },
    { "name": "Bolivia (Plurinational State of)", "code": "BO", "code3": "BOL", "numeric": 68, "langueages": ["es", "qu", "ay"] },
    { "name": "Bonaire, Sint Eustatius and Saba", "code": "BQ", "code3": "BES", "numeric": 535, "langueages": ["nl"] },
    { "name": "Bosnia and Herzegovina", "code": "BA", "code3": "BIH", "numeric": 70, "langueages": ["bs", "hr", "sr"] },
    { "name": "Botswana", "code": "BW", "code3": "BWA", "numeric": 72, "langueages": ["en", "tn"] },
    { "name": "Bouvet Island", "code": "BV", "code3": "BVT", "numeric": 74, "langueages": [] },
    { "name": "Brazil", "code": "BR", "code3": "BRA", "numeric": 76, "langueages": ["pt"] },
    { "name": "British Indian Ocean Territory (the)", "code": "IO", "code3": "IOT", "numeric": 86, "langueages": ["en"] },
    { "name": "Brunei Darussalam", "code": "BN", "code3": "BRN", "numeric": 96, "langueages": ["ms"] },
    { "name": "Bulgaria", "code": "BG", "code3": "BGR", "numeric": 100, "langueages": ["bg"] },
    { "name": "Burkina Faso", "code": "BF", "code3": "BFA", "numeric": 854, "langueages": ["fr"] },
    { "name": "Burundi", "code": "BI", "code3": "BDI", "numeric": 108, "langueages": ["fr", "rn"] },
    { "name": "Cabo Verde", "code": "CV", "code3": "CPV", "numeric": 132, "langueages": ["pt"] },
    { "name": "Cambodia", "code": "KH", "code3": "KHM", "numeric": 116, "langueages": ["km"] },
    { "name": "Cameroon", "code": "CM", "code3": "CMR", "numeric": 120, "langueages": ["fr", "en"] },
    { "name": "Canada", "code": "CA", "code3": "CAN", "numeric": 124, "langueages": ["en", "fr"] },
    { "name": "Cayman Islands (the)", "code": "KY", "code3": "CYM", "numeric": 136, "langueages": ["en"] },
    { "name": "Central African Republic (the)", "code": "CF", "code3": "CAF", "numeric": 140, "langueages": ["fr", "sg"] },
    { "name": "Chad", "code": "TD", "code3": "TCD", "numeric": 148, "langueages": ["fr", "ar"] },
    { "name": "Chile", "code": "CL", "code3": "CHL", "numeric": 152, "langueages": ["es"] },
    { "name": "China", "code": "CN", "code3": "CHN", "numeric": 156, "langueages": ["zh"] },
    { "name": "Christmas Island", "code": "CX", "code3": "CXR", "numeric": 162, "langueages": ["en"] },
    { "name": "Cocos (Keeling) Islands (the)", "code": "CC", "code3": "CCK", "numeric": 166, "langueages": ["en"] },
    { "name": "Colombia", "code": "CO", "code3": "COL", "numeric": 170, "langueages": ["es"] },
    { "name": "Comoros (the)", "code": "KM", "code3": "COM", "numeric": 174, "langueages": ["ar", "fr", "zd"] },
    { "name": "Congo (the Democratic Republic of the)", "code": "CD", "code3": "COD", "numeric": 180, "langueages": ["fr", "ln", "kg", "sw", "lu"] },
    { "name": "Congo (the)", "code": "CG", "code3": "COG", "numeric": 178, "langueages": ["fr", "ln"] },
    { "name": "Cook Islands (the)", "code": "CK", "code3": "COK", "numeric": 184, "langueages": ["en", "rar"] },
    { "name": "Costa Rica", "code": "CR", "code3": "CRI", "numeric": 188, "langueages": ["es"] },
    { "name": "Croatia", "code": "HR", "code3": "HRV", "numeric": 191, "langueages": ["hr"] },
    { "name": "Cuba", "code": "CU", "code3": "CUB", "numeric": 192, "langueages": ["es"] },
    { "name": "Curaçao", "code": "CW", "code3": "CUW", "numeric": 531, "langueages": ["nl", "pap", "en"] },
    { "name": "Cyprus", "code": "CY", "code3": "CYP", "numeric": 196, "langueages": ["el", "tr"] },
    { "name": "Czechia", "code": "CZ", "code3": "CZE", "numeric": 203, "langueages": ["cs"] },
    { "name": "Côte d'Ivoire", "code": "CI", "code3": "CIV", "numeric": 384, "langueages": ["fr"] },
    { "name": "Denmark", "code": "DK", "code3": "DNK", "numeric": 208, "langueages": ["da"] },
    { "name": "Djibouti", "code": "DJ", "code3": "DJI", "numeric": 262, "langueages": ["fr", "ar"] },
    { "name": "Dominica", "code": "DM", "code3": "DMA", "numeric": 212, "langueages": ["en"] },
    { "name": "Dominican Republic (the)", "code": "DO", "code3": "DOM", "numeric": 214, "langueages": ["es"] },
    { "name": "Ecuador", "code": "EC", "code3": "ECU", "numeric": 218, "langueages": ["es", "qu", "shp"] },
    { "name": "Egypt", "code": "EG", "code3": "EGY", "numeric": 818, "langueages": ["ar"] },
    { "name": "El Salvador", "code": "SV", "code3": "SLV", "numeric": 222, "langueages": ["es"] },
    { "name": "Equatorial Guinea", "code": "GQ", "code3": "GNQ", "numeric": 226, "langueages": ["es", "fr", "pt"] },
    { "name": "Eritrea", "code": "ER", "code3": "ERI", "numeric": 232, "langueages": ["ti", "ar", "en"] },
    { "name": "Estonia", "code": "EE", "code3": "EST", "numeric": 233, "langueages": ["et"] },
    { "name": "Eswatini", "code": "SZ", "code3": "SWZ", "numeric": 748, "langueages": ["en", "ss"] },
    { "name": "Ethiopia", "code": "ET", "code3": "ETH", "numeric": 231, "langueages": ["am"] },
    { "name": "Falkland Islands (the) [Malvinas]", "code": "FK", "code3": "FLK", "numeric": 238, "langueages": ["en"] },
    { "name": "Faroe Islands (the)", "code": "FO", "code3": "FRO", "numeric": 234, "langueages": ["fo", "da"] },
    { "name": "Fiji", "code": "FJ", "code3": "FJI", "numeric": 242, "langueages": ["en", "fj", "hi", "ur"] },
    { "name": "Finland", "code": "FI", "code3": "FIN", "numeric": 246, "langueages": ["fi", "sv"] },
    { "name": "France", "code": "FR", "code3": "FRA", "numeric": 250, "langueages": ["fr"] },
    { "name": "French Guiana", "code": "GF", "code3": "GUF", "numeric": 254, "langueages": ["fr"] },
    { "name": "French Polynesia", "code": "PF", "code3": "PYF", "numeric": 258, "langueages": ["fr", "ty"] },
    { "name": "French Southern Territories (the)", "code": "TF", "code3": "ATF", "numeric": 260, "langueages": ["fr"] },
    { "name": "Gabon", "code": "GA", "code3": "GAB", "numeric": 266, "langueages": ["fr"] },
    { "name": "Gambia (the)", "code": "GM", "code3": "GMB", "numeric": 270, "langueages": ["en"] },
    { "name": "Georgia", "code": "GE", "code3": "GEO", "numeric": 268, "langueages": ["ka"] },
    { "name": "Germany", "code": "DE", "code3": "DEU", "numeric": 276, "langueages": ["de"] },
    { "name": "Ghana", "code": "GH", "code3": "GHA", "numeric": 288, "langueages": ["en"] },
    { "name": "Gibraltar", "code": "GI", "code3": "GIB", "numeric": 292, "langueages": ["en"] },
    { "name": "Greece", "code": "GR", "code3": "GRC", "numeric": 300, "langueages": ["el"] },
    { "name": "Greenland", "code": "GL", "code3": "GRL", "numeric": 304, "langueages": ["kl", "da"] },
    { "name": "Grenada", "code": "GD", "code3": "GRD", "numeric": 308, "langueages": ["en"] },
    { "name": "Guadeloupe", "code": "GP", "code3": "GLP", "numeric": 312, "langueages": ["fr"] },
    { "name": "Guam", "code": "GU", "code3": "GUM", "numeric": 316, "langueages": ["en", "ch"] },
    { "name": "Guatemala", "code": "GT", "code3": "GTM", "numeric": 320, "langueages": ["es"] },
    { "name": "Guernsey", "code": "GG", "code3": "GGY", "numeric": 831, "langueages": ["en"] },
    { "name": "Guinea", "code": "GN", "code3": "GIN", "numeric": 324, "langueages": ["fr"] },
    { "name": "Guinea-Bissau", "code": "GW", "code3": "GNB", "numeric": 624, "langueages": ["pt"] },
    { "name": "Guyana", "code": "GY", "code3": "GUY", "numeric": 328, "langueages": ["en"] },
    { "name": "Haiti", "code": "HT", "code3": "HTI", "numeric": 332, "langueages": ["fr", "ht"] },
    { "name": "Heard Island and McDonald Islands", "code": "HM", "code3": "HMD", "numeric": 334, "langueages": [] },
    { "name": "Holy See (the)", "code": "VA", "code3": "VAT", "numeric": 336, "langueages": ["la", "it"] },
    { "name": "Honduras", "code": "HN", "code3": "HND", "numeric": 340, "langueages": ["es"] },
    { "name": "Hong Kong", "code": "HK", "code3": "HKG", "numeric": 344, "langueages": ["zh", "en"] },
    { "name": "Hungary", "code": "HU", "code3": "HUN", "numeric": 348, "langueages": ["hu"] },
    { "name": "Iceland", "code": "IS", "code3": "ISL", "numeric": 352, "langueages": ["is"] },
    { "name": "India", "code": "IN", "code3": "IND", "numeric": 356, "langueages": ["hi", "en"] },
    { "name": "Indonesia", "code": "ID", "code3": "IDN", "numeric": 360, "langueages": ["id"] },
    { "name": "Iran (Islamic Republic of)", "code": "IR", "code3": "IRN", "numeric": 364, "langueages": ["fa"] },
    { "name": "Iraq", "code": "IQ", "code3": "IRQ", "numeric": 368, "langueages": ["ar", "ku"] },
    { "name": "Ireland", "code": "IE", "code3": "IRL", "numeric": 372, "langueages": ["en", "ga"] },
    { "name": "Isle of Man", "code": "IM", "code3": "IMN", "numeric": 833, "langueages": ["en", "gv"] },
    { "name": "Israel", "code": "IL", "code3": "ISR", "numeric": 376, "langueages": ["he", "ar"] },
    { "name": "Italy", "code": "IT", "code3": "ITA", "numeric": 380, "langueages": ["it"] },
    { "name": "Jamaica", "code": "JM", "code3": "JAM", "numeric": 388, "langueages": ["en"] },
    { "name": "Japan", "code": "JP", "code3": "JPN", "numeric": 392, "langueages": ["ja"] },
    { "name": "Jersey", "code": "JE", "code3": "JEY", "numeric": 832, "langueages": ["en", "fr"] },
    { "name": "Jordan", "code": "JO", "code3": "JOR", "numeric": 400, "langueages": ["ar"] },
    { "name": "Kazakhstan", "code": "KZ", "code3": "KAZ", "numeric": 398, "langueages": ["kk", "ru"] },
    { "name": "Kenya", "code": "KE", "code3": "KEN", "numeric": 404, "langueages": ["en", "sw"] },
    { "name": "Kiribati", "code": "KI", "code3": "KIR", "numeric": 296, "langueages": ["en", "gil"] },
    { "name": "Korea (the Democratic People's Republic of)", "code": "KP", "code3": "PRK", "numeric": 408, "langueages": ["ko"] },
    { "name": "Korea (the Republic of)", "code": "KR", "code3": "KOR", "numeric": 410, "langueages": ["ko"] },
    { "name": "Kuwait", "code": "KW", "code3": "KWT", "numeric": 414, "langueages": ["ar"] },
    { "name": "Kyrgyzstan", "code": "KG", "code3": "KGZ", "numeric": 417, "langueages": ["ky", "ru"] },
    { "name": "Lao People's Democratic Republic (the)", "code": "LA", "code3": "LAO", "numeric": 418, "langueages": ["lo"] },
    { "name": "Latvia", "code": "LV", "code3": "LVA", "numeric": 428, "langueages": ["lv"] },
    { "name": "Lebanon", "code": "LB", "code3": "LBN", "numeric": 422, "langueages": ["ar", "fr"] },
    { "name": "Lesotho", "code": "LS", "code3": "LSO", "numeric": 426, "langueages": ["en", "st"] },
    { "name": "Liberia", "code": "LR", "code3": "LBR", "numeric": 430, "langueages": ["en"] },
    { "name": "Libya", "code": "LY", "code3": "LBY", "numeric": 434, "langueages": ["ar"] },
    { "name": "Liechtenstein", "code": "LI", "code3": "LIE", "numeric": 438, "langueages": ["de"] },
    { "name": "Lithuania", "code": "LT", "code3": "LTU", "numeric": 440, "langueages": ["lt"] },
    { "name": "Luxembourg", "code": "LU", "code3": "LUX", "numeric": 442, "langueages": ["fr", "de", "lb"] },
    { "name": "Macao", "code": "MO", "code3": "MAC", "numeric": 446, "langueages": ["zh", "pt"] },
    { "name": "Madagascar", "code": "MG", "code3": "MDG", "numeric": 450, "langueages": ["fr", "mg"] },
    { "name": "Malawi", "code": "MW", "code3": "MWI", "numeric": 454, "langueages": ["en", "ny"] },
    { "name": "Malaysia", "code": "MY", "code3": "MYS", "numeric": 458, "langueages": ["ms"] },
    { "name": "Maldives", "code": "MV", "code3": "MDV", "numeric": 462, "langueages": ["dv"] },
    { "name": "Mali", "code": "ML", "code3": "MLI", "numeric": 466, "langueages": ["fr"] },
    { "name": "Malta", "code": "MT", "code3": "MLT", "numeric": 470, "langueages": ["mt", "en"] },
    { "name": "Marshall Islands (the)", "code": "MH", "code3": "MHL", "numeric": 584, "langueages": ["en", "mh"] },
    { "name": "Martinique", "code": "MQ", "code3": "MTQ", "numeric": 474, "langueages": ["fr"] },
    { "name": "Mauritania", "code": "MR", "code3": "MRT", "numeric": 478, "langueages": ["ar"] },
    { "name": "Mauritius", "code": "MU", "code3": "MUS", "numeric": 480, "langueages": ["en", "fr"] },
    { "name": "Mayotte", "code": "YT", "code3": "MYT", "numeric": 175, "langueages": ["fr"] },
    { "name": "Mexico", "code": "MX", "code3": "MEX", "numeric": 484, "langueages": ["es"] },
    { "name": "Micronesia (Federated States of)", "code": "FM", "code3": "FSM", "numeric": 583, "langueages": ["en"] },
    { "name": "Moldova (the Republic of)", "code": "MD", "code3": "MDA", "numeric": 498, "langueages": ["ro"] },
    { "name": "Monaco", "code": "MC", "code3": "MCO", "numeric": 492, "langueages": ["fr"] },
    { "name": "Mongolia", "code": "MN", "code3": "MNG", "numeric": 496, "langueages": ["mn"] },
    { "name": "Montenegro", "code": "ME", "code3": "MNE", "numeric": 499, "langueages": ["sr", "bs", "sq", "hr"] },
    { "name": "Montserrat", "code": "MS", "code3": "MSR", "numeric": 500, "langueages": ["en"] },
    { "name": "Morocco", "code": "MA", "code3": "MAR", "numeric": 504, "langueages": ["ar", "ber"] },
    { "name": "Mozambique", "code": "MZ", "code3": "MOZ", "numeric": 508, "langueages": ["pt"] },
    { "name": "Myanmar", "code": "MM", "code3": "MMR", "numeric": 104, "langueages": ["my"] },
    { "name": "Namibia", "code": "NA", "code3": "NAM", "numeric": 516, "langueages": ["en"] },
    { "name": "Nauru", "code": "NR", "code3": "NRU", "numeric": 520, "langueages": ["en", "na"] },
    { "name": "Nepal", "code": "NP", "code3": "NPL", "numeric": 524, "langueages": ["ne"] },
    { "name": "Netherlands (the)", "code": "NL", "code3": "NLD", "numeric": 528, "langueages": ["nl"] },
    { "name": "New Caledonia", "code": "NC", "code3": "NCL", "numeric": 540, "langueages": ["fr"] },
    { "name": "New Zealand", "code": "NZ", "code3": "NZL", "numeric": 554, "langueages": ["en", "mi"] },
    { "name": "Nicaragua", "code": "NI", "code3": "NIC", "numeric": 558, "langueages": ["es"] },
    { "name": "Niger (the)", "code": "NE", "code3": "NER", "numeric": 562, "langueages": ["fr"] },
    { "name": "Nigeria", "code": "NG", "code3": "NGA", "numeric": 566, "langueages": ["en"] },
    { "name": "Niue", "code": "NU", "code3": "NIU", "numeric": 570, "langueages": ["niu", "en"] },
    { "name": "Norfolk Island", "code": "NF", "code3": "NFK", "numeric": 574, "langueages": ["en"] },
    { "name": "Northern Mariana Islands (the)", "code": "MP", "code3": "MNP", "numeric": 580, "langueages": ["en", "ch", "car"] },
    { "name": "Norway", "code": "NO", "code3": "NOR", "numeric": 578, "langueages": ["no", "nb", "nn"] },
    { "name": "Oman", "code": "OM", "code3": "OMN", "numeric": 512, "langueages": ["ar"] },
    { "name": "Pakistan", "code": "PK", "code3": "PAK", "numeric": 586, "langueages": ["ur", "en"] },
    { "name": "Palau", "code": "PW", "code3": "PLW", "numeric": 585, "langueages": ["en", "pau", "jpn", "sov", "tox", "angaur"] },
    { "name": "Palestine, State of", "code": "PS", "code3": "PSE", "numeric": 275, "langueages": ["ar"] },
    { "name": "Panama", "code": "PA", "code3": "PAN", "numeric": 591, "langueages": ["es"] },
    { "name": "Papua New Guinea", "code": "PG", "code3": "PNG", "numeric": 598, "langueages": ["en", "ho", "meu", "tpi"] },
    { "name": "Paraguay", "code": "PY", "code3": "PRY", "numeric": 600, "langueages": ["es", "gn"] },
    { "name": "Peru", "code": "PE", "code3": "PER", "numeric": 604, "langueages": ["es", "qu", "ay"] },
    { "name": "Philippines (the)", "code": "PH", "code3": "PHL", "numeric": 608, "langueages": ["en", "fil"] },
    { "name": "Pitcairn", "code": "PN", "code3": "PCN", "numeric": 612, "langueages": ["en"] },
    { "name": "Poland", "code": "PL", "code3": "POL", "numeric": 616, "langueages": ["pl"] },
    { "name": "Portugal", "code": "PT", "code3": "PRT", "numeric": 620, "langueages": ["pt"] },
    { "name": "Puerto Rico", "code": "PR", "code3": "PRI", "numeric": 630, "langueages": ["es", "en"] },
    { "name": "Qatar", "code": "QA", "code3": "QAT", "numeric": 634, "langueages": ["ar"] },
    { "name": "Republic of North Macedonia", "code": "MK", "code3": "MKD", "numeric": 807, "langueages": ["mk"] },
    { "name": "Romania", "code": "RO", "code3": "ROU", "numeric": 642, "langueages": ["ro"] },
    { "name": "Russian Federation (the)", "code": "RU", "code3": "RUS", "numeric": 643, "langueages": ["ru"] },
    { "name": "Rwanda", "code": "RW", "code3": "RWA", "numeric": 646, "langueages": ["rw", "en", "fr"] },
    { "name": "Réunion", "code": "RE", "code3": "REU", "numeric": 638, "langueages": ["fr"] },
    { "name": "Saint Barthélemy", "code": "BL", "code3": "BLM", "numeric": 652, "langueages": ["fr"] },
    { "name": "Saint Helena, Ascension and Tristan da Cunha", "code": "SH", "code3": "SHN", "numeric": 654, "langueages": ["en"] },
    { "name": "Saint Kitts and Nevis", "code": "KN", "code3": "KNA", "numeric": 659, "langueages": ["en"] },
    { "name": "Saint Lucia", "code": "LC", "code3": "LCA", "numeric": 662, "langueages": ["en"] },
    { "name": "Saint Martin (French part)", "code": "MF", "code3": "MAF", "numeric": 663, "langueages": ["fr"] },
    { "name": "Saint Pierre and Miquelon", "code": "PM", "code3": "SPM", "numeric": 666, "langueages": ["fr"] },
    { "name": "Saint Vincent and the Grenadines", "code": "VC", "code3": "VCT", "numeric": 670, "langueages": ["en"] },
    { "name": "Samoa", "code": "WS", "code3": "WSM", "numeric": 882, "langueages": ["sm", "en"] },
    { "name": "San Marino", "code": "SM", "code3": "SMR", "numeric": 674, "langueages": ["it"] },
    { "name": "Sao Tome and Principe", "code": "ST", "code3": "STP", "numeric": 678, "langueages": ["pt"] },
    { "name": "Saudi Arabia", "code": "SA", "code3": "SAU", "numeric": 682, "langueages": ["ar"] },
    { "name": "Senegal", "code": "SN", "code3": "SEN", "numeric": 686, "langueages": ["fr"] },
    { "name": "Serbia", "code": "RS", "code3": "SRB", "numeric": 688, "langueages": ["sr"] },
    { "name": "Seychelles", "code": "SC", "code3": "SYC", "numeric": 690, "langueages": ["fr", "en", "crs"] },
    { "name": "Sierra Leone", "code": "SL", "code3": "SLE", "numeric": 694, "langueages": ["en"] },
    { "name": "Singapore", "code": "SG", "code3": "SGP", "numeric": 702, "langueages": ["en", "ms", "ta", "zh"] },
    { "name": "Sint Maarten (Dutch part)", "code": "SX", "code3": "SXM", "numeric": 534, "langueages": ["nl", "en"] },
    { "name": "Slovakia", "code": "SK", "code3": "SVK", "numeric": 703, "langueages": ["sk"] },
    { "name": "Slovenia", "code": "SI", "code3": "SVN", "numeric": 705, "langueages": ["sl"] },
    { "name": "Solomon Islands", "code": "SB", "code3": "SLB", "numeric": 90, "langueages": ["en"] },
    { "name": "Somalia", "code": "SO", "code3": "SOM", "numeric": 706, "langueages": ["so", "ar"] },
    { "name": "South Africa", "code": "ZA", "code3": "ZAF", "numeric": 710, "langueages": ["af", "en", "nr", "st", "ss", "tn", "ts", "ve", "xh", "zu"] },
    { "name": "South Georgia and the South Sandwich Islands", "code": "GS", "code3": "SGS", "numeric": 239, "langueages": ["en"] },
    { "name": "South Sudan", "code": "SS", "code3": "SSD", "numeric": 728, "langueages": ["en"] },
    { "name": "Spain", "code": "ES", "code3": "ESP", "numeric": 724, "langueages": ["es", "ca", "eu", "gl"] },
    { "name": "Sri Lanka", "code": "LK", "code3": "LKA", "numeric": 144, "langueages": ["si", "ta"] },
    { "name": "Sudan (the)", "code": "SD", "code3": "SDN", "numeric": 729, "langueages": ["ar", "en"] },
    { "name": "Suriname", "code": "SR", "code3": "SUR", "numeric": 740, "langueages": ["nl"] },
    { "name": "Svalbard and Jan Mayen", "code": "SJ", "code3": "SJM", "numeric": 744, "langueages": ["no"] },
    { "name": "Sweden", "code": "SE", "code3": "SWE", "numeric": 752, "langueages": ["sv"] },
    { "name": "Switzerland", "code": "CH", "code3": "CHE", "numeric": 756, "langueages": ["de", "fr", "it", "rm"] },
    { "name": "Syrian Arab Republic", "code": "SY", "code3": "SYR", "numeric": 760, "langueages": ["ar"] },
    { "name": "Taiwan (Province of China)", "code": "TW", "code3": "TWN", "numeric": 158, "langueages": ["zh"] },
    { "name": "Tajikistan", "code": "TJ", "code3": "TJK", "numeric": 762, "langueages": ["tg", "ru"] },
    { "name": "Tanzania, United Republic of", "code": "TZ", "code3": "TZA", "numeric": 834, "langueages": ["sw", "en"] },
    { "name": "Thailand", "code": "TH", "code3": "THA", "numeric": 764, "langueages": ["th"] },
    { "name": "Timor-Leste", "code": "TL", "code3": "TLS", "numeric": 626, "langueages": ["pt", "tet"] },
    { "name": "Togo", "code": "TG", "code3": "TGO", "numeric": 768, "langueages": ["fr"] },
    { "name": "Tokelau", "code": "TK", "code3": "TKL", "numeric": 772, "langueages": ["tkl", "en"] },
    { "name": "Tonga", "code": "TO", "code3": "TON", "numeric": 776, "langueages": ["to", "en"] },
    { "name": "Trinidad and Tobago", "code": "TT", "code3": "TTO", "numeric": 780, "langueages": ["en"] },
    { "name": "Tunisia", "code": "TN", "code3": "TUN", "numeric": 788, "langueages": ["ar"] },
    { "name": "Turkey", "code": "TR", "code3": "TUR", "numeric": 792, "langueages": ["tr"] },
    { "name": "Turkmenistan", "code": "TM", "code3": "TKM", "numeric": 795, "langueages": ["tk", "ru"] },
    { "name": "Turks and Caicos Islands (the)", "code": "TC", "code3": "TCA", "numeric": 796, "langueages": ["en"] },
    { "name": "Tuvalu", "code": "TV", "code3": "TUV", "numeric": 798, "langueages": ["en", "tvl"] },
    { "name": "Uganda", "code": "UG", "code3": "UGA", "numeric": 800, "langueages": ["en", "sw"] },
    { "name": "Ukraine", "code": "UA", "code3": "UKR", "numeric": 804, "langueages": ["uk"] },
    { "name": "United Arab Emirates (the)", "code": "AE", "code3": "ARE", "numeric": 784, "langueages": ["ar"] },
    { "name": "United Kingdom of Great Britain and Northern Ireland (the)", "code": "GB", "code3": "GBR", "numeric": 826, "langueages": ["en"] },
    { "name": "United States Minor Outlying Islands (the)", "code": "UM", "code3": "UMI", "numeric": 581, "langueages": ["en"] },
    { "name": "United States of America (the)", "code": "US", "code3": "USA", "numeric": 840, "langueages": ["en"] },
    { "name": "Uruguay", "code": "UY", "code3": "URY", "numeric": 858, "langueages": ["es"] },
    { "name": "Uzbekistan", "code": "UZ", "code3": "UZB", "numeric": 860, "langueages": ["uz"] },
    { "name": "Vanuatu", "code": "VU", "code3": "VUT", "numeric": 548, "langueages": ["bi", "en", "fr"] },
    { "name": "Venezuela (Bolivarian Republic of)", "code": "VE", "code3": "VEN", "numeric": 862, "langueages": ["es"] },
    { "name": "Viet Nam", "code": "VN", "code3": "VNM", "numeric": 704, "langueages": ["vi"] },
    { "name": "Virgin Islands (British)", "code": "VG", "code3": "VGB", "numeric": 92, "langueages": ["en"] },
    { "name": "Virgin Islands (U.S.)", "code": "VI", "code3": "VIR", "numeric": 850, "langueages": ["en"] },
    { "name": "Wallis and Futuna", "code": "WF", "code3": "WLF", "numeric": 876, "langueages": ["fr"] },
    { "name": "Western Sahara", "code": "EH", "code3": "ESH", "numeric": 732, "langueages": ["ar", "es"] },
    { "name": "Yemen", "code": "YE", "code3": "YEM", "numeric": 887, "langueages": ["ar"] },
    { "name": "Zambia", "code": "ZM", "code3": "ZMB", "numeric": 894, "langueages": ["en"] },
    { "name": "Zimbabwe", "code": "ZW", "code3": "ZWE", "numeric": 716, "langueages": ["en", "sn", "nd"] },
    { "name": "Åland Islands", "code": "AX", "code3": "ALA", "numeric": 248, "langueages": ["sv"] },
];

export default countries;