// Định nghĩa kiểu dữ liệu cho Language
export interface Language {
    code: string;
    name: string;
}

export const languages: Language[] = [
    { "code": "en", "name": "English" },
    { "code": "vi", "name": "Tiếng Việt" },
    { "code": "zh", "name": "中文" },
    { "code": "zh-TW", "name": "繁體中文 (台灣)" },
    { "code": "ru", "name": "Русский" },
    { "code": "es", "name": "Español" },
    { "code": "fr", "name": "Français" },
    { "code": "de", "name": "Deutsch" },
    { "code": "it", "name": "Italiano" },
    { "code": "pt", "name": "Português" },
    { "code": "ja", "name": "日本語" },
    { "code": "ko", "name": "한국어" },
    { "code": "ar", "name": "العربية" },
    { "code": "hi", "name": "हिन्दी" },
    { "code": "bn", "name": "বাংলা" },
    { "code": "pa", "name": "ਪੰਜਾਬੀ" },
    { "code": "jv", "name": "Basa Jawa" },
    { "code": "ms", "name": "Bahasa Melayu" },
    { "code": "id", "name": "Bahasa Indonesia" },
    { "code": "tr", "name": "Türkçe" },
    { "code": "fa", "name": "فارسی" },
    { "code": "ur", "name": "اردو" },
    { "code": "ta", "name": "தமிழ்" },
    { "code": "te", "name": "తెలుగు" },
    { "code": "mr", "name": "मराठी" },
    { "code": "th", "name": "ไทย" },
    { "code": "pl", "name": "Polski" },
    { "code": "uk", "name": "Українська" },
    { "code": "ro", "name": "Română" },
    { "code": "nl", "name": "Nederlands" },
    { "code": "el", "name": "Ελληνικά" },
    { "code": "sv", "name": "Svenska" },
    { "code": "fi", "name": "Suomi" },
    { "code": "no", "name": "Norsk" },
    { "code": "da", "name": "Dansk" },
    { "code": "cs", "name": "Čeština" },
    { "code": "hu", "name": "Magyar" },
    { "code": "he", "name": "עברית" },
    { "code": "sr", "name": "Српски" },
    { "code": "sk", "name": "Slovenčina" },
    { "code": "bg", "name": "Български" },
    { "code": "hr", "name": "Hrvatski" },
    { "code": "lt", "name": "Lietuvių" },
    { "code": "lv", "name": "Latviešu" },
    { "code": "et", "name": "Eesti" },
    { "code": "sl", "name": "Slovenščina" },
    { "code": "ca", "name": "Català" },
    { "code": "eu", "name": "Euskara" },
    { "code": "gl", "name": "Galego" },
    { "code": "af", "name": "Afrikaans" },
    { "code": "sw", "name": "Kiswahili" },
    { "code": "zu", "name": "isiZulu" },
    { "code": "xh", "name": "isiXhosa" },
    { "code": "st", "name": "Sesotho" },
    { "code": "so", "name": "Soomaali" },
    { "code": "am", "name": "አማርኛ" },
    { "code": "yo", "name": "Yorùbá" },
    { "code": "ig", "name": "Igbo" },
    { "code": "ha", "name": "Hausa" },
    { "code": "my", "name": "မြန်မာဘာသာ" },
    { "code": "km", "name": "ភាសាខ្មែរ" },
    { "code": "lo", "name": "ພາສາລາວ" },
    { "code": "si", "name": "සිංහල" },
    { "code": "ne", "name": "नेपाली" },
    { "code": "mn", "name": "Монгол" },
    { "code": "uz", "name": "Oʻzbekcha" },
    { "code": "kk", "name": "Қазақша" },
    { "code": "az", "name": "Azərbaycanca" },
    { "code": "ka", "name": "ქართული" },
    { "code": "hy", "name": "Հայերեն" },
    { "code": "ps", "name": "پښتو" },
    { "code": "tg", "name": "Тоҷикӣ" },
    { "code": "tk", "name": "Türkmençe" },
    { "code": "ky", "name": "Кыргызча" },
    { "code": "bs", "name": "Bosanski" },
    { "code": "mk", "name": "Македонски" },
    { "code": "sq", "name": "Shqip" },
    { "code": "is", "name": "Íslenska" },
    { "code": "mt", "name": "Malti" },
    { "code": "ga", "name": "Gaeilge" },
    { "code": "cy", "name": "Cymraeg" },
    { "code": "be", "name": "Беларуская" },
    { "code": "lb", "name": "Lëtzebuergesch" },
    { "code": "fo", "name": "Føroyskt" },
    { "code": "qu", "name": "Runa Simi" },
    { "code": "ay", "name": "Aymar aru" },
    { "code": "gn", "name": "Avañe'ẽ" },
    { "code": "ht", "name": "Kreyòl ayisyen" },
    { "code": "sm", "name": "Gagana Samoa" },
    { "code": "to", "name": "Faka Tonga" },
    { "code": "fj", "name": "Vosa Vakaviti" },
    { "code": "haw", "name": "ʻŌlelo Hawaiʻi" }
];



export default languages;